// Linha do tempo de prêmios e reconhecimentos, ordenada por data (mais antigo -> mais recente)
export const premiosTimeline = [
  {
    id: 1,
    ano: '2019',
    titulo: 'Voto de Aplausos pelas Contribuições Municipais',
    instituicao: 'Câmara Municipal de Lagoa de Itaenga - PE',
    imagem: 'https://somosconexaosocial.org/site_img/premiacoes/06.jpg',
    descricao: 'Voto de aplausos concedido pela Câmara Municipal de Lagoa de Itaenga pelas contribuições prestadas ao desenvolvimento social do município.',
  },
  {
    id: 2,
    ano: '2020',
    titulo: 'Homenagem à Defesa dos Direitos da Criança e do Adolescente',
    instituicao: 'Conselheiro Tutelar Dijailson C. de Sousa',
    imagem: 'https://somosconexaosocial.org/site_img/premiacoes/02.jpg',
    descricao: 'Homenagem pela dedicação à proteção e à promoção dos direitos humanos de crianças e adolescentes.',
  },
  {
    id: 3,
    ano: '2020',
    titulo: 'Voto de Aplausos pelos Serviços Prestados na Pandemia',
    instituicao: 'Câmara Municipal de Lagoa de Itaenga - PE',
    imagem: 'https://somosconexaosocial.org/site_img/premiacoes/06.jpg',
    descricao: 'Voto de aplausos em reconhecimento aos serviços prestados à população durante o período de pandemia.',
  },
  {
    id: 4,
    ano: '2023',
    titulo: 'Prêmio Excelência SERTA',
    instituicao: 'SERTA',
    imagem: 'https://somosconexaosocial.org/site_img/premiacoes/03.jpg',
    descricao: 'Reconhecimento e mérito concedidos pelo SERTA pelo trabalho desenvolvido junto às comunidades atendidas pela associação.',
  },
  {
    id: 5,
    ano: '2023',
    titulo: 'Moção de Agradecimento',
    instituicao: 'Câmara Municipal de Lagoa de Itaenga - PE',
    imagem: 'https://somosconexaosocial.org/site_img/premiacoes/04.jpg',
    descricao: 'Agradecimento formal pela execução de projetos que promovem cidadania, inclusão e desenvolvimento no município.',
  },
  {
    id: 6,
    ano: '2023',
    titulo: 'Melhor Organização Municipal',
    instituicao: 'Pesquisa Universo Destaque',
    imagem: 'https://somosconexaosocial.org/site_img/premiacoes/05.jpg',
    descricao: 'Certificado de melhor organização municipal, resultado da Pesquisa Universo Destaque realizada em Lagoa de Itaenga.',
  },
  {
    id: 7,
    ano: '2026',
    titulo: 'Medalha Rute Bacelar de Defesa dos Direitos da Pessoa Idosa',
    instituicao: 'Assembleia Legislativa de Pernambuco (ALEPE)',
    imagem: 'https://somosconexaosocial.org/site_img/premiacoes/01.jpg',
    descricao: 'Medalha concedida pela Assembleia Legislativa de Pernambuco em reconhecimento ao trabalho de defesa dos direitos da pessoa idosa.',
  },
];
