
CREATE DATABASE IF NOT EXISTS doacoes_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;


USE doacoes_db;

CREATE TABLE doacoes (

id INT AUTO_INCREMENT PRIMARY KEY,
brindeEscolhido VARCHAR(50) NOT NULL,
celular VARCHAR(20) NOT NULL,
cidade VARCHAR(100) NOT NULL,
complemento VARCHAR(255) NOT NULL,
endereco VARCHAR(255) NOT NULL,
numero VARCHAR(20) NOT NULL,
dataDoacao DATETIME NOT NULL,
email VARCHAR(150) NOT NULL,
nome VARCHAR(150) NOT NULL,
valorDoado DECIMAL(10,2) NOT NULL,
criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    senha VARCHAR(255) NOT NULL
    );